export const _QUESTION_TYPE = {
  TEXT: 'TEXT',
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  ATTACH_FILE: 'ATTACH_FILE',
  DATE: 'DATE',
  DESCRIPTIVE: 'DESCRIPTIVE',
  NUMBER: 'NUMBER',
} as const;

export type _QUESTION_TYPE = typeof _QUESTION_TYPE[keyof typeof _QUESTION_TYPE];